### PR TITLE
NPE fix from mods brock breakers.

### PR DESCRIPTION
**Pull request by Scorpi**
Fixed NPE when mod machine breaks a block.
Fix for: RedPower, BuildCraft, IndustrialCraft.

Special thanks for muCkk. =)

### CODE REVIEW

**Comment by zford** [comment]
If these plugins are introducing an NPE somewhere, can we just fix the NPE and fail fast instead of introducing magic numbers?

**Comment by Scorpi** [comment]
I know no other way to fix that NPE.
And that's not a plugin's, that's a mods.

**Comment by zford** [comment]
> I know no other way to fix that NPE.

By checking for null on the critical section?

**Comment by Scorpi** [comment]
Well, do it as you want, I will check your fix.

**Comment by zford** [comment]
I don't understand the bug, I don't use Tekkit, and I don't have an interest in fixing or testing against it.  However, if you're going to submit an NPE fix, you ought to show me the use case, and actually fix the NPE.  This is not an NPE fix, you're checking against a non-null variable.

**Comment by Scorpi** [comment]
It's not tekkit. http://mcportcentral.co.za/
If block breaks not by player entity, it causes exception because your plugin can't pay to a block =\

**Pull request closed without merging**
